"""init schema

Revision ID: 9be161fa8ad4
Revises: 
Create Date: 2025-12-12 01:05:05.933572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be161fa8ad4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('bin_iin', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_index(op.f('ix_suppliers_supplier_id'), 'suppliers', ['supplier_id'], unique=False)
    op.create_table('units',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_index(op.f('ix_units_unit_id'), 'units', ['unit_id'], unique=False)
    op.create_table('materials',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], ),
    sa.PrimaryKeyConstraint('material_id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_materials_material_id'), 'materials', ['material_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('warehouse_id')
    )
    op.create_index(op.f('ix_warehouses_warehouse_id'), 'warehouses', ['warehouse_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('po_id')
    )
    op.create_index(op.f('ix_purchase_orders_po_id'), 'purchase_orders', ['po_id'], unique=False)
    op.create_table('supplier_material_prices',
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('price_id'),
    sa.UniqueConstraint('supplier_id', 'material_id', 'price_date', name='uq_supplier_price_date')
    )
    op.create_index(op.f('ix_supplier_material_prices_price_id'), 'supplier_material_prices', ['price_id'], unique=False)
    op.create_table('supplier_materials',
    sa.Column('sup_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('min_order_qty', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('sup_id'),
    sa.UniqueConstraint('supplier_id', 'material_id', name='uq_supplier_material')
    )
    op.create_index(op.f('ix_supplier_materials_sup_id'), 'supplier_materials', ['sup_id'], unique=False)
    op.create_table('warehouse_material_policy',
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('min_stock', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('warehouse_id', 'material_id'),
    sa.UniqueConstraint('warehouse_id', 'material_id', name='pk_warehouse_material_policy')
    )
    op.create_table('po_items',
    sa.Column('po_item_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty_ordered', sa.Numeric(), nullable=False),
    sa.Column('unit_price', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.po_id'], ),
    sa.PrimaryKeyConstraint('po_item_id'),
    sa.UniqueConstraint('po_id', 'material_id', name='uq_po_material')
    )
    op.create_index(op.f('ix_po_items_po_item_id'), 'po_items', ['po_item_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.Column('move_type', sa.String(), nullable=False),
    sa.Column('move_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('from_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('to_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('related_po_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(), nullable=False),
    sa.Column('unit_price', sa.Numeric(), nullable=True),
    sa.Column('ext_doc_no', sa.String(), nullable=True),
    sa.Column('ext_doc_date', sa.Date(), nullable=True),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('shipped_by_name', sa.String(), nullable=True),
    sa.Column('accepted_by_name', sa.String(), nullable=True),
    sa.Column('ship_date', sa.Date(), nullable=True),
    sa.Column('load_date', sa.Date(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], ),
    sa.ForeignKeyConstraint(['related_po_id'], ['purchase_orders.po_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('move_id')
    )
    op.create_index(op.f('ix_stock_movements_move_id'), 'stock_movements', ['move_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_move_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_po_items_po_item_id'), table_name='po_items')
    op.drop_table('po_items')
    op.drop_table('warehouse_material_policy')
    op.drop_index(op.f('ix_supplier_materials_sup_id'), table_name='supplier_materials')
    op.drop_table('supplier_materials')
    op.drop_index(op.f('ix_supplier_material_prices_price_id'), table_name='supplier_material_prices')
    op.drop_table('supplier_material_prices')
    op.drop_index(op.f('ix_purchase_orders_po_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_warehouses_warehouse_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_materials_material_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_units_unit_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_suppliers_supplier_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
